// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025–present Iron Curtain contributors

//! Tests for the `.aud` asset wrapper and loader.

use super::*;

/// Confirms that the Bevy loader claims the expected Westwood audio extension.
///
/// This protects the asset-pipeline contract used by higher-level engine code
/// when it requests legacy C&C sound assets by file extension.
#[test]
fn aud_loader_extensions_match_expected_format() {
    let loader = AudLoader;
    assert_eq!(loader.extensions(), &["aud"]);
}

/// Proves that the wrapper delegates parsing to `cnc-formats` and preserves
/// the parsed header metadata.
///
/// The test uses generated bytes instead of an external fixture so the proof
/// remains deterministic and easy to understand in isolation.
#[test]
fn aud_audio_parses_header_via_cnc_formats() {
    let samples = [120i16, -80, 32, -16];
    // The parser crate can generate a valid `.aud` payload for tests, which
    // keeps this proof self-contained and easy to audit.
    let bytes = cnc_aud::build_aud(&samples, 22_050, false);
    let aud = AudAudio::parse(bytes).expect("valid AUD should parse");

    assert_eq!(aud.header.sample_rate, 22_050);
    assert!(!aud.header.is_stereo());
    assert_eq!(
        aud.file().expect("stored bytes stay parseable").header,
        aud.header
    );
}
